FORMAT: 1A
HOST: http://localhost:3001

# Sleep Tracker API

This is a REST API for tracking sleep periods (e.g. for a toddler) for multiple people.
A person may have multiple sleep periods, and all sleep periods belong to one person.

## People Collection [/people]

### List All People [GET]

Lists all people, their names, birthdays, and ID numbers.

+ Response 200 (application/json)

        [
            {
                "birthdate": "1999-05-02",
                "created_at": "2019-11-26T00:27:49.364Z",
                "id": 20,
                "name": "John Sample",
                "updated_at": "2019-11-26T00:27:49.364Z"
            },
            {
                "birthdate": "2004-08-31",
                "created_at": "2019-11-26T00:28:08.786Z",
                "id": 21,
                "name": "Jane Sample",
                "updated_at": "2019-11-26T00:28:08.786Z"
            }
        ]

### Create a New Person [POST]

This action creates a new person.
The `name` parameter is required; the `birthday` parameter is optional.
The format of the `birthday` will be auto-interpreted, so you may pass `"12 May 2015"`, `"May 12, 2015"`, "`2015-05-12`", etc.

+ Request (application/json)

        {
            "name": "Erica Sample",
            "birthdate": "12 August 2017"
        }

+ Response 201 (application/json)

    + Body

            {
                "birthdate": "2017-08-12",
                "created_at": "2019-11-26T00:32:27.955Z",
                "id": 22,
                "name": "Erica Sample",
                "updated_at": "2019-11-26T00:32:27.955Z"
            }
            
## Actions On Specific People [/people/{person_id}]
            
### Edit a Person [PUT]

This action edits an existing person.
Pass the `name` or `birthdate` you wish to edit in the payload.

+ Request (application/json)

        {
            "birthdate": "15 August 2017"
        }
    
+ Response 204 (application/json)

### Delete a Person [DELETE]

This action deletes an existing person.

+ Response 204